---
- name: Update base-devel
  become: true
  community.general.pacman:
    name: base-devel
    state: latest

- name: Update pacman cache
  become: true
  community.general.pacman:
    update_cache: true

- name: System upgrade
  become: true
  community.general.pacman:
    upgrade: true
